### PR TITLE
chore: Formatting, linting and manual revisions

### PR DESCRIPTION
**Pull request by umgefahren**
Hi!

I really like your project, seeing it on LinkedIn.

I wanted to implement some standard practices to keep the code standard and pretty.

Feel free to ask any questions about the changes I made.

- **Add .gitignore**
- **Run clippy --fix**
- **Implement clippy suggestions**
- **Run cargo fmt**
- **Implement automatic fixes from clippy pedantic**
- **Implement more suggestions by clippy::pedantic**

### CODE REVIEW

**Comment by bones-ai** [comment]
Hey, thanks for the PR, I'll have a look at it when I get some free time.
Also I don't post on LinkedIn, is there a link to the post you saw?

**Comment by umgefahren** [comment]
Here is the post: https://www.linkedin.com/feed/update/urn:li:activity:7224757111858036736?utm_source=share&utm_medium=member_ios

**Comment by bones-ai** [comment]
Hey,
Thanks a lot for sharing, 
I'm unable to view the post though, says "This post cannot be displayed"

**Comment by umgefahren** [comment]
image
Here is a screenshot

**Comment by bones-ai** [comment]
Nice, thank you :)

**Comment by bones-ai** [comment]
Hey, 
Just had a look at this, everything looks good.
Thanks for the changes :)

**Pull request merged**
